# NumPy Arrays - Part 3<br>
NumPy - 대규모의 다차원 배열을 쉽게 처리할 때 사용하는 파이썬 라이브러리<br>

원본 출처: Introduction to Deep Learning at Carnegie Mellon University (https://deeplearning.cs.cmu.edu/S22/index.html)

In [1]:
# Import the NumPy
import numpy as np

## 1. 데이터 읽어오기

### a. 인덱싱: NumPy 배열에서 값 읽어오기

In [12]:
# TODO: 무작위 값으로 채워진 4 x 5 x 6 배열을 만들어보세요. (5 x 6 행렬이 4개 묶음 있는 것으로 해석할 수 있음)
# numpy.random.rand (https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)
n = np.random.rand(4,5,6)
n.shape

(4, 5, 6)

나중에 다룰 MNIST (필기체 인식) 데이터셋의 모양은 (60000, 28, 28)인데
28 (행의 수, 높이) x 28 (열의 수, 너비)의 그림 60000만장이 있는 것으로 해석됩니다.

In [11]:
# TODO: n에서 두 번째 묶음의 세 번째 행, 네 번째 열의 값은? (인덱스는 0에서 시작함)

n[1][2][3]

0.31649953064130376

### b. 슬라이싱: NumPy 배열의 일부를 가져오기

시작(포함):끝(미포함)으로 연속된 항목을 슬라이싱 <br>
:만 쓰면 전체

In [13]:
# 첫 번째 묶음의 모든 행렬 가져오기
print(n[0, :, :]) # same as: n[0], 정답이므로 수정할 필요 없음

[[0.82375802 0.2623115  0.88351701 0.10185996 0.57922729 0.00802955]
 [0.80991113 0.137525   0.08837093 0.92709266 0.17931124 0.60959297]
 [0.728517   0.0374076  0.27492085 0.08552825 0.19859059 0.1851328 ]
 [0.11193909 0.41434304 0.77724838 0.56130489 0.91775593 0.73001685]
 [0.07814961 0.04663193 0.12691945 0.61367074 0.53482375 0.1852402 ]]


In [14]:
# TODO: 첫 번째 묶음에서 [0, 3) 행, [0, 4) 열 가져오기, 즉 3 x 4 배열이 나와야 함
print(n[0,0:3 ,0:4 ])

[[0.82375802 0.2623115  0.88351701 0.10185996]
 [0.80991113 0.137525   0.08837093 0.92709266]
 [0.728517   0.0374076  0.27492085 0.08552825]]


In [15]:
# TODO: 전체 묶음에서 4번 째 행, 5번째 열 값들 가져오기
print(n[:,3 ,4 ])

[0.91775593 0.72187366 0.42902997 0.21493118]


### c. Slicing at Interval
시작::증가폭(스텝)으로 띄엄띄엄 슬라이싱<br>
예) a[7::2]인 경우 a[7], a[9], a[11], ... 을 가져와서 배열로 만듦

In [16]:
# TODO: 0번 묶음, 2번 묶음, 4번 묶음, ... 슬라이싱 (n은 3번 묶음까지만 있어서 두 개의 묶음만 출력됨)
print(n[0::2])

[[[0.82375802 0.2623115  0.88351701 0.10185996 0.57922729 0.00802955]
  [0.80991113 0.137525   0.08837093 0.92709266 0.17931124 0.60959297]
  [0.728517   0.0374076  0.27492085 0.08552825 0.19859059 0.1851328 ]
  [0.11193909 0.41434304 0.77724838 0.56130489 0.91775593 0.73001685]
  [0.07814961 0.04663193 0.12691945 0.61367074 0.53482375 0.1852402 ]]

 [[0.25637024 0.98357073 0.39477887 0.4690165  0.65033236 0.1795868 ]
  [0.31126037 0.97715583 0.91160694 0.82821758 0.15963149 0.39576552]
  [0.93883002 0.02939002 0.34815693 0.93188555 0.33381754 0.14194367]
  [0.61161562 0.4634956  0.7211883  0.5938127  0.42902997 0.81575902]
  [0.38493651 0.11038959 0.1805806  0.6164132  0.83279114 0.15963726]]]


원래 n의 모습과 비교해가며 아래의 결과는 어떻게 만들어진 것인지 이해하고 넘어가세요.

In [17]:
print(n[0::2, 1:4, 1::2])

[[[0.137525   0.92709266 0.60959297]
  [0.0374076  0.08552825 0.1851328 ]
  [0.41434304 0.56130489 0.73001685]]

 [[0.97715583 0.82821758 0.39576552]
  [0.02939002 0.93188555 0.14194367]
  [0.4634956  0.5938127  0.81575902]]]


## 2. 데이터 수정하기

In [18]:
# 배열 복사하기
n_copy = np.copy(n)

### a. 하나의 값 수정하기

In [19]:
# 복사한 배열과 n이 같은지 하나의 항목 확인
print(n_copy[2, 4, 1] == n[2, 4, 1])

True


In [24]:
# TODO: 복사한 배열 n_copy[2, 4, 1]의 값을 0.005로 변경
n_copy[2,4,1]= 0.005

# 여전히 내용이 같은지 확인
print(n_copy[2, 4, 1] == n[2, 4, 1])

False


n_copy는 n을 복사한 것이지만 n과 다른 위치에 독립적으로 존재한다. 만약 copy 함수로 복사하지 않고 m = n으로 m을 만든다음 m[2, 4, 1] 값을 수정하면 어떻게 될까?

In [23]:
print('Before: ', n[2, 4, 1])
m = n
m[2, 4, 1] = 0.5
print('After: ', n[2, 4, 1])

Before:  0.11038959284460148
After:  0.5


In [25]:
# n, m, n_copy가 저장된 장소 출력
print(id(n))
print(id(m))
print(id(n_copy))

139938706259184
139938706259184
139938706259472


### b. 여러 항목의 값을 같은 값으로 수정하기

In [26]:
n_copy = np.copy(n)

# n_copy 3번째 묶음의 4번째 행의 값 확인
print(n_copy[2, 3])

[0.61161562 0.4634956  0.7211883  0.5938127  0.42902997 0.81575902]


In [27]:
# TODO: n_copy 3번째 묶음 4번째 행의 값을 모두 0.5로 바꾸기
n_copy[2, 3] = 0.5

# n_copy 3번째 묶음 4번째 행의 값 확인
print(n_copy[2, 3])

[0.5 0.5 0.5 0.5 0.5 0.5]
