# NumPy Arrays - Part 4<br>

by uramoon@kw.ac.kr<br>
원본 출처: Introduction to Deep Learning at Carnegie Mellon University (https://deeplearning.cs.cmu.edu/S22/index.html)

In [1]:
# Import the NumPy
import numpy as np

## Reshaping Arrays (배열의 모양을 다르게 해석하기)<br>

Array reshaping은 배열안의 데이터는 그대로 두고 모양을 바꿔 해석을 다르게 하는 것입니다.

예를 들어 (4,) 모양의 1차원 배열 [1, 2, 3, 4]는 (4, 1) 모양의 2차원 배열 [[1], [2], [3], [4]], <br> 또는 (2, 2) 모양의 2차원 배열 [[1, 2], [3, 4]] 및 (1, 4) 모양의 2차원 배열 [[1, 2, 3, 4]]로 형태를 바꿔 해석할 수도 있습니다.

- (4)는 괄호 안에 들어있는 숫자 4를 의미
- (4,)는 1차원 배열의 생김새를 의미(길이:4)

### 동일 차원으로 reshaping

In [2]:
s = np.random.rand(3, 4, 5)
print(f"원래 모양: {s.shape}")

원래 모양: (3, 4, 5)


***TODO: s의 전체 원소 개수 구하기***
* Q: 어떻게 계산할 수 있을까요?
* A: 각 차원에 있는 숫자들을 곱한다.

In [3]:
s.size

60

In [4]:
# s 내용 확인하기
print(s)

[[[0.20303883 0.43556723 0.85240537 0.21770734 0.94257551]
  [0.1645916  0.31621595 0.95681305 0.48774896 0.04119012]
  [0.23154927 0.62866939 0.41977194 0.38452743 0.70223224]
  [0.04168762 0.09653899 0.46068486 0.1448691  0.30612051]]

 [[0.39261103 0.51617221 0.31294017 0.69580724 0.87859876]
  [0.38358416 0.4325291  0.4207681  0.13091169 0.28420541]
  [0.86613907 0.50875712 0.32940905 0.82255303 0.0041437 ]
  [0.39463797 0.39058777 0.80266429 0.60472902 0.30297328]]

 [[0.79535016 0.95578783 0.33224136 0.73528455 0.29335414]
  [0.20987075 0.01097599 0.68256776 0.84290642 0.89484978]
  [0.52154922 0.9610284  0.59652545 0.89430321 0.64509168]
  [0.32315684 0.0457538  0.62871733 0.37113419 0.42443021]]]


In [5]:
# TODO: s를 (2, 6, 5)로 reshape하여 s1에 저장하기
s1 = s.reshape(2,6 ,5 )
print(f"s1의 모양: {s1.shape}")

s1의 모양: (2, 6, 5)


In [6]:
# s와 s1의 원소값 순서 동일한 것을 확인해보세요.
print(s1)

[[[0.20303883 0.43556723 0.85240537 0.21770734 0.94257551]
  [0.1645916  0.31621595 0.95681305 0.48774896 0.04119012]
  [0.23154927 0.62866939 0.41977194 0.38452743 0.70223224]
  [0.04168762 0.09653899 0.46068486 0.1448691  0.30612051]
  [0.39261103 0.51617221 0.31294017 0.69580724 0.87859876]
  [0.38358416 0.4325291  0.4207681  0.13091169 0.28420541]]

 [[0.86613907 0.50875712 0.32940905 0.82255303 0.0041437 ]
  [0.39463797 0.39058777 0.80266429 0.60472902 0.30297328]
  [0.79535016 0.95578783 0.33224136 0.73528455 0.29335414]
  [0.20987075 0.01097599 0.68256776 0.84290642 0.89484978]
  [0.52154922 0.9610284  0.59652545 0.89430321 0.64509168]
  [0.32315684 0.0457538  0.62871733 0.37113419 0.42443021]]]


### 다른 차원으로 reshaping

In [7]:
# TODO: 0부터 119까지 120개의 정수로 이루어진 1차원 배열을 간단하게 만들어보세요.
# numpy.arange (https://numpy.org/doc/stable/reference/generated/numpy.arange.html)
r = np.arange(120)

In [8]:
print(f"원래 모양: {r.shape}")

원래 모양: (120,)


In [9]:
# TODO: (120,) -> (3, 4, 10)
# 원소개수는 120개로 동일합니다.
r1 = r.reshape(3,4,10)
print(f"r1의 모양: {r1.shape}")

r1의 모양: (3, 4, 10)


In [10]:
# r과 r1을 비교해보세요.
print(r)
print(r1)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]]

 [[ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]]

 [[ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 1

In [11]:
# TODO: r1을 reshape하여 r2에 저장하세요.
# (3, 4, 10) -> (6, 20)
r2 = r1.reshape(6,20)
print(f"r2의 모양: {r2.shape}")

r2의 모양: (6, 20)


In [12]:
# r2와 r1, r을 비교해보세요.
print(r1)
print(r2)

[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]]

 [[ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]]

 [[ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]]]
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109

## 배열 펼치기 (Flattening)
배열 펼치기는 다차원 배열을 일차원으로 만들어줍니다.<br>
일반적인 다층 퍼셉트론 인공 신경망은 일차원 배열을 입력으로 받기 때문에<br> MNIST 데이터셋을 사용하면 28 x 28 모양의 이차원 배열을 길이 784의 일차원 배열로 만들어 사용합니다.

In [13]:
k = np.random.rand(5, 6)
k

array([[0.40654864, 0.46218062, 0.79848023, 0.70996253, 0.78666276,
        0.41044246],
       [0.40821824, 0.13341063, 0.47543653, 0.84845497, 0.8100278 ,
        0.38058225],
       [0.06999544, 0.2928351 , 0.12392068, 0.53210349, 0.94079031,
        0.03857208],
       [0.5378806 , 0.87275879, 0.3956486 , 0.13094074, 0.75125501,
        0.16152325],
       [0.38633251, 0.18204648, 0.27301867, 0.31954776, 0.52061336,
        0.88918601]])

### 기본 순서대로 펼치기

In [14]:
# k와 k1을 비교해보세요.
k1 = k.flatten()
k1

array([0.40654864, 0.46218062, 0.79848023, 0.70996253, 0.78666276,
       0.41044246, 0.40821824, 0.13341063, 0.47543653, 0.84845497,
       0.8100278 , 0.38058225, 0.06999544, 0.2928351 , 0.12392068,
       0.53210349, 0.94079031, 0.03857208, 0.5378806 , 0.87275879,
       0.3956486 , 0.13094074, 0.75125501, 0.16152325, 0.38633251,
       0.18204648, 0.27301867, 0.31954776, 0.52061336, 0.88918601])

In [15]:
k1.shape

(30,)

## 배열 이어 붙이기
https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [16]:
# 2차원 배열인 array1과 array2 생성
array1 = np.array([[1, 2], [3, 4]])
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.array([[5, 6]])
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")

Array 1 is 
 [[1 2]
 [3 4]]  with dimensions  (2, 2) 

Array 2 is 
 [[5 6]]  with dimensions  (1, 2) 



배열을 이어붙일 때에는 기준이 되는 축 이외의 모양이 동일해야 합니다.<br>
1. (2, 2)와 (1, 2) 이어 붙일 때 0번 축으로 이어붙이면 (3, 2) 배열 탄생
2. (2, 2)와 (1, 2) 이어 붙일 때 1번 축으로 이어붙이면 0번 축의 모양이 서로 다르므로 이어붙이기 실패

In [17]:
# TODO: 0번 축을 기준으로 array1과 array2를 이어붙이세요.
concatenated_array1 = np.concatenate((array1, array2), axis=0)
print("Concatenated array 1 along axis 0 (row-wise for 2-d arrays) is \n", concatenated_array1, "with dimensions ", concatenated_array1.shape, '\n')

Concatenated array 1 along axis 0 (row-wise for 2-d arrays) is 
 [[1 2]
 [3 4]
 [5 6]] with dimensions  (3, 2) 



In [20]:
# TODO: 1번 축을 기준으로 array1과 array2를 이어붙이세요. (실패합니다. 에러 메시지를 확인하세요.)
concatenated_array2 = np.concatenate((array1,array2),axis=1)
print("Concatenated array 2 along axis 0 (column-wise for 2-d arrays) is \n", concatenated_array2, "with dimensions ", concatenated_array2.shape)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [21]:
# TODO: (3, 4, 5) 형태에 0 이상 3 미만의 무작위 정수로 채워진 배열을 만드세요.
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html
array1 = np.random.randint(3, size=(3,4,5))
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

Array 1 is 
 [[[1 0 2 1 2]
  [2 2 1 2 1]
  [0 1 1 1 1]
  [2 0 0 2 1]]

 [[1 1 2 2 2]
  [0 0 2 0 1]
  [1 1 1 0 1]
  [2 0 2 1 0]]

 [[0 2 1 2 0]
  [0 0 0 2 2]
  [1 0 1 1 2]
  [1 2 0 0 2]]]  with dimensions  (3, 4, 5) 



In [24]:
# TODO: (3, 4, 5) 형태에 0 이상 4 미만의 무작위 정수로 채워진 배열을 만드세요.
array2 = np.random.randint(4, size=(3,4,5))
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")

Array 2 is 
 [[[2 0 2 2 1]
  [3 1 3 0 1]
  [2 2 0 0 3]
  [0 3 2 3 2]]

 [[3 3 1 0 0]
  [1 1 3 1 2]
  [3 2 0 1 0]
  [1 1 0 2 1]]

 [[2 3 2 0 3]
  [2 0 3 0 1]
  [0 3 1 2 2]
  [2 0 0 1 0]]]  with dimensions  (3, 4, 5) 



***TODO: 0번 축을을 기준으로 이어붙이기***
* Q: 어떤 모양일까요? (코딩으로 결과 확인 전에 작성해보세요.)
* A: shape이 (6,4,5) 일 것이다.

In [25]:
# TODO: 0번 축을 기준으로 이어붙이기
concatenated_array1 = np.concatenate((array1, array2), axis=0)
print("Concatenated array 1 is \n", concatenated_array1, "\n\n", "and the dimensions of the concatenated array 1 are: \n", concatenated_array1.shape)

Concatenated array 1 is 
 [[[1 0 2 1 2]
  [2 2 1 2 1]
  [0 1 1 1 1]
  [2 0 0 2 1]]

 [[1 1 2 2 2]
  [0 0 2 0 1]
  [1 1 1 0 1]
  [2 0 2 1 0]]

 [[0 2 1 2 0]
  [0 0 0 2 2]
  [1 0 1 1 2]
  [1 2 0 0 2]]

 [[2 0 2 2 1]
  [3 1 3 0 1]
  [2 2 0 0 3]
  [0 3 2 3 2]]

 [[3 3 1 0 0]
  [1 1 3 1 2]
  [3 2 0 1 0]
  [1 1 0 2 1]]

 [[2 3 2 0 3]
  [2 0 3 0 1]
  [0 3 1 2 2]
  [2 0 0 1 0]]] 

 and the dimensions of the concatenated array 1 are: 
 (6, 4, 5)


***TODO: 1번 축을 기준으로 이어붙이기***
* Q: 어떤 모양일까요? (코딩으로 결과 확인 전에 작성해보세요.)
* A: shape이 (3,8,5) 일 것이다.

In [26]:
# TODO: 1번 축을 기준으로 이어붙이기
concatenated_array2 = np.concatenate((array1,array2),axis=1)
print("Concatenated array 2 is \n", concatenated_array2, "\n\n", "and the dimensions of the concatenated array 2 are: \n", concatenated_array2.shape)

Concatenated array 2 is 
 [[[1 0 2 1 2]
  [2 2 1 2 1]
  [0 1 1 1 1]
  [2 0 0 2 1]
  [2 0 2 2 1]
  [3 1 3 0 1]
  [2 2 0 0 3]
  [0 3 2 3 2]]

 [[1 1 2 2 2]
  [0 0 2 0 1]
  [1 1 1 0 1]
  [2 0 2 1 0]
  [3 3 1 0 0]
  [1 1 3 1 2]
  [3 2 0 1 0]
  [1 1 0 2 1]]

 [[0 2 1 2 0]
  [0 0 0 2 2]
  [1 0 1 1 2]
  [1 2 0 0 2]
  [2 3 2 0 3]
  [2 0 3 0 1]
  [0 3 1 2 2]
  [2 0 0 1 0]]] 

 and the dimensions of the concatenated array 2 are: 
 (3, 8, 5)


***TODO: 2번 축을 기준으로 이어붙이기***
* Q: 어떤 모양일까요? (코딩으로 결과 확인 전에 작성해보세요.)
* A: shape이 (3,4,10) 일 것이다.

In [27]:
# TODO: 2번 축을 기준으로 이어붙이기
concatenated_array3 = np.concatenate((array1,array2),axis=2)
print("Concatenated array 3 is \n", concatenated_array3, "\n\n", "and the dimensions of the concatenated array 3 are: \n", concatenated_array3.shape)

Concatenated array 3 is 
 [[[1 0 2 1 2 2 0 2 2 1]
  [2 2 1 2 1 3 1 3 0 1]
  [0 1 1 1 1 2 2 0 0 3]
  [2 0 0 2 1 0 3 2 3 2]]

 [[1 1 2 2 2 3 3 1 0 0]
  [0 0 2 0 1 1 1 3 1 2]
  [1 1 1 0 1 3 2 0 1 0]
  [2 0 2 1 0 1 1 0 2 1]]

 [[0 2 1 2 0 2 3 2 0 3]
  [0 0 0 2 2 2 0 3 0 1]
  [1 0 1 1 2 0 3 1 2 2]
  [1 2 0 0 2 2 0 0 1 0]]] 

 and the dimensions of the concatenated array 3 are: 
 (3, 4, 10)
